package questions

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/suryanshu-09/holy_grail/internal/apperr"
)

// Filter narrows the questions returned by List.
type Filter struct {
	DocumentID string
	TopicID    string
	Year       *int
	Subject    string
	Limit      int
	Offset     int
}

// repository is the SQL implementation of questions.Repository.
type repository struct {
	db *sql.DB
}

// NewRepository creates a questions repository.
func NewRepository(db *sql.DB) Repository {
	return &repository{db: db}
}

const questionColumns = `q.id, q.document_id, q.question_number, q.question_text, q.page_number, q.start_page, q.end_page, q.start_offset, q.end_offset, q.confidence, q.question_type, q.options_json, q.extraction_notes_json, q.images_json, q.year, q.subject, q.difficulty, q.created_at, q.updated_at`

// Insert persists a new question into the database. The question ID is
// generated by the database (gen_random_uuid()). Nullable fields may be nil.
func (r *repository) Insert(ctx context.Context, q Question) error {
	_, err := r.db.ExecContext(ctx,
		`INSERT INTO questions (id, document_id, question_number, question_text, page_number, start_page, end_page, start_offset, end_offset, confidence, question_type, options_json, extraction_notes_json, images_json, year, subject, difficulty)
		 VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)`,
		q.DocumentID, q.QuestionNumber, q.QuestionText, q.PageNumber, q.StartPage, q.EndPage, q.StartOffset, q.EndOffset, q.Confidence, q.QuestionType, q.OptionsJSON, q.ExtractionNotesJSON, q.ImagesJSON, q.Year, q.Subject, q.Difficulty)
	if err != nil {
		return fmt.Errorf("questions: insert: %w", err)
	}
	return nil
}

// List returns questions matching the filter. TopicID filters through the
// question_topics join table.
func (r *repository) List(ctx context.Context, f Filter) ([]Question, error) {
	query := strings.Builder{}
	query.WriteString("SELECT " + questionColumns + " FROM questions q WHERE 1=1")

	var args []interface{}
	if f.DocumentID != "" {
		args = append(args, f.DocumentID)
		query.WriteString(fmt.Sprintf(" AND q.document_id = $%d", len(args)))
	}
	if f.TopicID != "" {
		query.WriteString(" AND EXISTS (SELECT 1 FROM question_topics qt WHERE qt.question_id = q.id AND qt.topic_id = $" + fmt.Sprint(len(args)+1) + ")")
		args = append(args, f.TopicID)
	}
	if f.Year != nil {
		args = append(args, *f.Year)
		query.WriteString(fmt.Sprintf(" AND q.year = $%d", len(args)))
	}
	if f.Subject != "" {
		args = append(args, f.Subject)
		query.WriteString(fmt.Sprintf(" AND q.subject = $%d", len(args)))
	}

	args = append(args, f.Limit)
	query.WriteString(fmt.Sprintf(" ORDER BY q.created_at DESC LIMIT $%d OFFSET $%d", len(args), len(args)+1))
	args = append(args, f.Offset)

	rows, err := r.db.QueryContext(ctx, query.String(), args...)
	if err != nil {
		return nil, fmt.Errorf("questions: list: %w", err)
	}
	defer rows.Close()

	qs := make([]Question, 0)
	for rows.Next() {
		var q Question
		if err := rows.Scan(&q.ID, &q.DocumentID, &q.QuestionNumber, &q.QuestionText,
			&q.PageNumber, &q.StartPage, &q.EndPage, &q.StartOffset, &q.EndOffset, &q.Confidence, &q.QuestionType, &q.OptionsJSON, &q.ExtractionNotesJSON, &q.ImagesJSON, &q.Year, &q.Subject, &q.Difficulty, &q.CreatedAt, &q.UpdatedAt); err != nil {
			return nil, fmt.Errorf("questions: scan: %w", err)
		}
		qs = append(qs, q)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("questions: rows: %w", err)
	}
	return qs, nil
}

// GetByID returns a single question by ID or apperr.ErrNotFound.
func (r *repository) GetByID(ctx context.Context, id string) (Question, error) {
	var q Question
	err := r.db.QueryRowContext(ctx,
		"SELECT "+questionColumns+" FROM questions q WHERE q.id = $1", id).
		Scan(&q.ID, &q.DocumentID, &q.QuestionNumber, &q.QuestionText,
			&q.PageNumber, &q.StartPage, &q.EndPage, &q.StartOffset, &q.EndOffset, &q.Confidence, &q.QuestionType, &q.OptionsJSON, &q.ExtractionNotesJSON, &q.ImagesJSON, &q.Year, &q.Subject, &q.Difficulty, &q.CreatedAt, &q.UpdatedAt)
	if err == sql.ErrNoRows {
		return Question{}, apperr.ErrNotFound
	}
	if err != nil {
		return Question{}, fmt.Errorf("questions: get by id: %w", err)
	}
	return q, nil
}
